### ISSUE TITLE
 python-Levenshtein on PyPI?

### ISSUE THREAD

**Issue by keikoro** [ztane/python-Levenshtein#26]
Hi there, after a quick look around, it's not entirely clear if this fork corresponds to the [python-Levenshtein package on PyPI](https://pypi.python.org/pypi/python-Levenshtein), i.e. if I'll get this version of the package if I install it via PyPI or the old one.

The `README` says: "This package was long missing from PyPi and available as source checkout only. We needed to restore this package for Go Mobile for Plone and Pywurfl projects which depend on this." but the actual PyPI page isn't linked?

I would have compared version numbers but I didn't see any mentioned on here either.

**Comment by ztane** [comment]
@kerstin Yeah this is the package that is python-Levenshtein on PyPI. The version number is in [setup.py](https://github.com/ztane/python-Levenshtein/blob/master/setup.py).

**Comment by kerstin** [comment]
Thanks!

Would it make sense to make that more clear in the README  – particularly for casual/drive-by readers – possibly with a backlink? I could make such a change and send a PR.

**Comment by kerstin** [comment]
Thx!

And true about the linkage, though only if one clicks through (and then it depends on which version one clicks on). Maybe this confused me – I'm used to seeing all info presented on the "top level" package page. Not sure how that is accomplished, however.

(Just checked and it looks like most packages only have their most recent version listed in the first place and that and the "top level" page are then the same.)
