### ISSUE TITLE
Expectations from a maintainer?

### ISSUE THREAD

**Issue by creatorrr** [ztane/python-Levenshtein#74]
Read the notice about needing a maintainer for this project, is this still something you are looking for? I frequently use this package at work and I would love to see how one could help out. 

> Maintainer wanted
> 
> I am looking for a new maintainer to the project as it is apparent that I haven’t had the need for this particular library for well over > 7 years now, due to it being a C-only library and its somewhat restrictive original license.

**Comment by maxbachmann** [comment]
Issue https://github.com/ztane/python-Levenshtein/issues/61 already lists some people who would be interested in helping to maintain the package as well. It appears that @ztane did not really have time to look into this in the last months.

**Comment by creatorrr** [comment]
Gotcha, thanks! Closing in favor of #61
