### ISSUE TITLE
Please provide typing hints

### ISSUE THREAD

**Issue by nthykier** [ztane/python-Levenshtein#87]
I am using this module from a code base that use python typing hints with `mypy` to help us catch mistakes. This leads to the error from `mypy`

```
error: Skipping analyzing "Levenshtein": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```

The `py.typed` marker file is a reference [PEP-0561](https://peps.python.org/pep-0561/)

In this case, a `__init__.pyi` is probably as well needed due to the implementation being in C.

**Comment by maxbachmann** [comment]
The library is maintained in https://github.com/rapidfuzz/Levenshtein nowadays and should be typed + include the py.typed marker.

**Comment by nthykier** [comment]
Thanks.

I have asked the Debian maintainer to rebase the packaging to use that repo instead of this one (Debian's package still referenced this as the upstream project).

**Comment by maxbachmann** [comment]
Ah yes the new version depends on rapidfuzz, which only got packaged on debian a couple weeks ago. So I think it's only in debian sid so far. Just a matter of time though.
